apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:  
        spec:
          containers:
          - name: clearsessions
            image: django-backend:latest
            imagePullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: django-secret
            command: ['sh', '-c', './manage.py clearsessions']
          restartPolicy: OnFailure
      backoffLimit: 4    