apiVersion: batch/v1
kind: Job
metadata:
  name: django-createsuperuser
spec:
  ttlSecondsAfterFinished: 600
  template:  
    spec:
      containers:
      - name: django-createsuperuser
        image: mrdave95/django_site:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: postgres
                key: dsn    
        envFrom:
          - secretRef:
              name: django-secret
          - secretRef:
              name: django-superuser-secret
        command: ['sh', '-c', './manage.py createsuperuser --noinput']
      restartPolicy: OnFailure
  backoffLimit: 4    