apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          volumeMounts:
            - mountPath: "/.postgresql"
              name: pg-root-cert
              readOnly: true
          command:
            - psql
            - "host=rc1b-j03a218khoxjlwdi.mdb.yandexcloud.net port=6432 sslmode=require dbname=edu-stoic-dubinsky user=edu-stoic-dubinsky target_session_attrs=read-write"
      volumes:
        - name: pg-root-cert
          secret:
            secretName: pg-root-cert
            defaultMode: 384
